---
title: "SARP_timeseries"
author: "DennieT"
date: "2023-07-07"
output: pdf_document
---


```{r}
library(readr)
library(tidyr)
library(ggplot2)
library("tidyverse")
library(ggplot2)
library(plyr)
library('pracma')
library(lubridate)
library("dplyr")
```



#Set working directory
```{r}
setwd("C:/Users/denni/Documents/RStudioSARP")
```



#Import Data
```{r}
DATA <- read.csv("CBPtimeseries.csv", header=TRUE) #header TRUE mean first line of csv has heading

```

#Make SampleDate into Datetime format
```{r}
DATA <- DATA %>%
   mutate(Date = ymd(DATA$SampleDate))
```



```{r}

DATA <- DATA %>% 
  mutate(year = year(DATA$Date),
         month = month(DATA$Date),
         day = day(DATA$Date),
         doy = yday(DATA$Date))

#Combine rows
DATA2 <- DATA %>%
  group_by(EventId, Station, SampleDate) %>%
  summarise_at(vars(2:5), mean, na.rm = TRUE) #var(2) --> count # columns to 2 from SampleDate

```



```{r, fig.height = 4, fig.width=8}

CHL_Timeseries <- DATA2 %>%
  ggplot(aes(x = Date, y=CHLA,color = factor(Station)))+
  geom_line(size=0.8, alpha=0.9) + #scale_x_date(date_labels = "%Y")+
  facet_wrap(~year,nrow = 1,scales = "free_x") +
  theme(axis.text.x = element_text(angle = 90, vjust =0.5, hjust = 0.5))+
  xlab('Date') + ylab('CHL-a (ug/L)')+
  guides(color = guide_legend(title = 'Station'))+
  labs(title = "Chl-a in situ Timeseries of all Stations") +
  scale_x_date(date_labels = "%b %d") +
  scale_color_manual(values=c('Red','Blue','limegreen','Purple','Brown'))+
  theme_light()


png(filename = 'CHL_Timeseries.png', height = 2800, width = 12000, res = 500) 
#defines png, res is in dpi, h & w in pixels

CHL_Timeseries
dev.off()

```
```

